export const BANK_LIST = [
	'AB Bank Ltd.',
	'Airtel Payments Bank Ltd',
	'American Express Banking Corporation',
	'Andhra Pradesh Grameena Bank',
	'Arunachal Pradesh Rural Bank',
	'Assam Gramin Bank',
	'Au Small Finance Bank Ltd.',
	'Australia and New Zealand Banking Group Ltd.',
	'Axis Bank Ltd.',
	'Bank of America',
	'Bank of Bahrain and Kuwait B.S.C.',
	'Bank of Baroda',
	'Bank of Ceylon',
	'Bank of China Limited',
	'Bank of India',
	'Bank of Maharashtra',
	'Bank of Nova Scotia',
	'Bandhan Bank Ltd.',
	'Barclays Bank Plc.',
	'Bihar Gramin Bank',
	'BNP Paribas',
	'Canara Bank',
	'Capital Small Finance Bank Ltd',
	'Central Bank of India',
	'Chhattisgarh Gramin Bank',
	'Citibank N.A.',
	'City Union Bank Ltd.',
	'Coastal Local Area Bank Ltd',
	'Cooperatieve Rabobank U.A./ Coöperatieve Centrale Raiffeisen-Boerenleenbank B.A.',
	'Credit Agricole Corporate and Investment Bank',
	'CSB Bank Limited',
	'CTBC Bank Co., Ltd.',
	'DBS Bank India Limited',
	'DCB Bank Ltd.',
	'Deutsche Bank A.G.',
	'Dhanlaxmi Bank Ltd.',
	'Doha Bank Q.P.S.C',
	'Emirates NBD Bank P.J.S.C',
	'Equitas Small Finance Bank Ltd',
	'ESAF Small Finance Bank Ltd.',
	'Export-Import Bank of India',
	'Federal Bank Ltd.',
	'FINO Payments Bank Ltd',
	'First Abu Dhabi Bank PJSC',
	'FirstRand Bank Limited',
	'Gujarat Gramin Bank',
	'Haryana Gramin Bank',
	'HDFC Bank Ltd',
	'Himachal Pradesh Gramin Bank',
	'Hong Kong and Shanghai Banking Corporation Limited',
	'IDBI Bank Limited',
	'IDFC FIRST Bank Limited',
	'India Post Payments Bank Ltd',
	'Indian Bank',
	'Indian Overseas Bank',
	'Industrial and Commercial Bank of China',
	'Industrial Bank of Korea',
	'IndusInd Bank Ltd',
	'Jammu & Kashmir Bank Ltd.',
	'Jammu and Kashmir Grameen Bank',
	'Jana Small Finance Bank Ltd',
	'Jharkhand Gramin Bank',
	'Jio Payments Bank Ltd',
	'J.P. Morgan Chase Bank N.A.',
	'JSC VTB Bank',
	'Karnataka Bank Ltd.',
	'Karnataka Grameena Bank',
	'Karur Vysya Bank Ltd.',
	'KEB Hana Bank',
	'Kerala Grameena Bank',
	'Kotak Mahindra Bank Ltd',
	'Krishna Bhima Samruddhi LAB Ltd',
	'Kookmin Bank',
	'Madhya Pradesh Gramin Bank',
	'Maharashtra Gramin Bank',
	'Manipur Rural Bank',
	'Mashreq bank P.S.C',
	'Meghalaya Rural Bank',
	'Mizoram Rural Bank',
	'Mizuho Bank Ltd.',
	'MUFG Bank, Ltd.',
	'Nagaland Rural Bank',
	'Nainital bank Ltd.',
	'NatWest Markets Plc',
	'National Bank for Agriculture and Rural Development',
	'National Housing Bank',
	'Nong Hyup Bank',
	'NSDL Payments Bank Limited',
	'Odisha Grameen Bank',
	'Paytm Payments Bank Ltd',
	'PT Bank Maybank Indonesia TBK',
	'Puducherry Grama Bank',
	'Punjab & Sind Bank',
	'Punjab Gramin Bank',
	'Punjab National Bank',
	'Qatar National Bank (Q.P.S.C.)',
	'Rajasthan Gramin Bank',
	'RBL Bank Ltd.',
	'SBM Bank (India) Limited',
	'Sberbank',
	'Shivalik Small Finance Bank Ltd',
	'Shinhan Bank',
	'slice Small Finance Bank Ltd.',
	'Small Industries Development Bank of India',
	'Societe Generale',
	'Sonali Bank Ltd.',
	'South Indian Bank Ltd.',
	'Standard Chartered Bank',
	'State Bank of India',
	'Sumitomo Mitsui Banking Corporation',
	'Suryoday Small Finance Bank Ltd.',
	'Tamil Nadu Grama Bank',
	'Tamilnad Mercantile Bank Ltd.',
	'Telangana Grameena Bank',
	'Tripura Gramin Bank',
	'UCO Bank',
	'Ujjivan Small Finance Bank Ltd.',
	'Union Bank of India',
	'United Overseas Bank Limited',
	'Unity Small Finance Bank Ltd',
	'Uttar Pradesh Gramin Bank',
	'Uttarakhand Gramin Bank',
	'UBS AG',
	'Utkarsh Small Finance Bank Ltd.',
	'West Bengal Gramin Bank',
	'Woori Bank',
	'YES Bank Ltd.',
];

export const EXPENSE_CATEGORIES = [
	{ key: 'transport', name: 'Transport', emoji: '🚗', color: '#FF6B6B' },
	{ key: 'in_laws', name: 'In Laws', emoji: '👨‍👩‍👧‍👦', color: '#4ECDC4' },
	{ key: 'gas', name: 'Gas', emoji: '🔥', color: '#45B7D1' },
	{
		key: 'snacks_desserts',
		name: 'Snacks & Desserts',
		emoji: '🍦',
		color: '#FFA07A',
	},
	{ key: 'medicine', name: 'Medicine', emoji: '💊', color: '#FFD700' },
	{
		key: 'ranchi_grocery',
		name: 'Ranchi Grocery',
		emoji: '🛒',
		color: '#98D8C8',
	},
	{
		key: 'kolkata_household',
		name: 'Kolkata Household',
		emoji: '🏠',
		color: '#A78BFA',
	},
	{
		key: 'rent_electricity',
		name: 'Rent & Electricity',
		emoji: '💡',
		color: '#F471B5',
	},
	{
		key: 'shivraj_maintenance',
		name: 'Shivraj Maintenance',
		emoji: '🔧',
		color: '#6EE7B7',
	},
	{
		key: 'entertainment',
		name: 'Entertainment',
		emoji: '🎬',
		color: '#F59E0B',
	},
	{ key: 'train', name: 'Train', emoji: '🚆', color: '#10B981' },
	{ key: 'petrol_bike', name: 'Petrol & Bike', emoji: '⛽', color: '#6366F1' },
	{
		key: 'wife_account',
		name: 'Wife Account & Cash',
		emoji: '👩',
		color: '#EC4899',
	},
	{
		key: 'wife_shopping',
		name: 'Wife Shopping & Parlour',
		emoji: '💄',
		color: '#8B5CF6',
	},
	{
		key: 'banking_charges',
		name: 'Banking & EMI Charges',
		emoji: '🏦',
		color: '#06B6D4',
	},
	{ key: 'wifi', name: 'Wifi', emoji: '📶', color: '#3B82F6' },
	{
		key: 'mobile_recharge',
		name: 'Mobile Recharge',
		emoji: '📱',
		color: '#EF4444',
	},
	{
		key: 'trading_charges',
		name: 'Trading Charges',
		emoji: '📈',
		color: '#84CC16',
	},
	{
		key: 'digital_gold',
		name: 'Digital Gold Charges',
		emoji: '💰',
		color: '#F59E0B',
	},
	{
		key: 'subscriptions',
		name: 'Subscriptions',
		emoji: '📺',
		color: '#8B5CF6',
	},
	{
		key: 'health_insurance',
		name: 'Health Insurance',
		emoji: '🏥',
		color: '#10B981',
	},
	{ key: 'street_food', name: 'Street Food', emoji: '🍢', color: '#F97316' },
	{ key: 'online_food', name: 'Online Food', emoji: '🍕', color: '#DC2626' },
	{ key: 'shopping', name: 'Online Shopping', emoji: '📦', color: '#7C3AED' },
	{ key: 'liquid', name: 'Liquid', emoji: '🥤', color: '#60A5FA' },
	{ key: 'donation', name: 'Donation', emoji: '🤲', color: '#059669' },
	{ key: 'neighbour', name: 'Neighbour', emoji: '🏡', color: '#6B7280' },
	{
		key: 'miscellaneous',
		name: 'Miscellaneous',
		emoji: '📝',
		color: '#9CA3AF',
	},
];

export const SAVINGS_CATEGORIES = [
	// Mutual Funds
	{
		key: 'tata_large_mid_cap',
		name: 'Tata Large & Mid Cap Fund',
		emoji: '📈',
		color: '#3B82F6',
	},
	{
		key: 'tata_small_cap',
		name: 'Tata Small Cap Fund',
		emoji: '📊',
		color: '#1D4ED8',
	},
	{
		key: 'tata_small_cap_direct',
		name: 'Tata Small Cap Fund - Direct',
		emoji: '🎯',
		color: '#2563EB',
	},
	{
		key: 'tata_gold_etf_fof',
		name: 'Tata Gold ETF Fund of Fund',
		emoji: '💰',
		color: '#F59E0B',
	},
	{
		key: 'uti_gold_etf_fof',
		name: 'UTI Gold ETF Fund of Fund',
		emoji: '🏦',
		color: '#D97706',
	},
	{
		key: 'uti_nifty_50',
		name: 'UTI Nifty 50 Index Fund',
		emoji: '📉',
		color: '#059669',
	},
	{
		key: 'uti_sensex',
		name: 'UTI S&P BSE SENSEX Index Fund',
		emoji: '📊',
		color: '#047857',
	},
	{ key: 'hdfc_gold', name: 'HDFC Gold Fund', emoji: '🥇', color: '#F59E0B' },
	{
		key: 'hdfc_nifty_50',
		name: 'HDFC Index Fund - NIFTY 50 Plan',
		emoji: '📈',
		color: '#DC2626',
	},
	{
		key: 'hdfc_sensex',
		name: 'HDFC Index Fund - S&P BSE SENSEX Plan',
		emoji: '📉',
		color: '#B91C1C',
	},
	{
		key: 'icici_equity',
		name: 'ICICI Prudential Retirement Fund Pure Equity Plan',
		emoji: '🏢',
		color: '#7C3AED',
	},
	{
		key: 'nippon_gold',
		name: 'Nippon India Gold Savings Fund',
		emoji: '🏅',
		color: '#F59E0B',
	},
	{
		key: 'nippon_small_cap',
		name: 'Nippon India Small Cap Fund',
		emoji: '📊',
		color: '#0EA5E9',
	},
	{ key: 'sbi_gold', name: 'SBI Gold Fund', emoji: '🥇', color: '#F59E0B' },
	{
		key: 'sbi_large_midcap',
		name: 'SBI Large & Midcap Fund',
		emoji: '📈',
		color: '#10B981',
	},
	{
		key: 'sbi_small_cap',
		name: 'SBI Small Cap Fund',
		emoji: '📊',
		color: '#0D9488',
	},
	{
		key: 'parag_parikh_flexi',
		name: 'Parag Parikh Flexi Cap Fund',
		emoji: '🎯',
		color: '#8B5CF6',
	},
	{
		key: 'canara_elss',
		name: 'Canara Robeco ELSS Tax Saver Fund',
		emoji: '💰',
		color: '#EF4444',
	},

	// Digital & ETFs
	{ key: 'digital_gold', name: 'Digital Gold', emoji: '💎', color: '#F59E0B' },
	{
		key: 'gold_etfs_total',
		name: 'Gold Exchange Traded Funds (Total)',
		emoji: '📊',
		color: '#D97706',
	},
	{
		key: 'shoonya_etfs_total',
		name: 'Shoonya Exchange Traded Funds (Total)',
		emoji: '📉',
		color: '#7C3AED',
	},
	{
		key: 'shoonya_shares_total',
		name: 'Shoonya Shares (Total)',
		emoji: '📈',
		color: '#10B981',
	},

	// Bonds & Fixed Income
	{
		key: 'floating_rate_bond',
		name: 'Floating Rate Savings Bond',
		emoji: '📋',
		color: '#06B6D4',
	},
	{
		key: 'treasury_bills',
		name: 'Treasury Bills',
		emoji: '🏛️',
		color: '#3B82F6',
	},

	// Insurance
	{
		key: 'lic',
		name: 'Life Insurance Corporation',
		emoji: '🛡️',
		color: '#EF4444',
	},

	// Recurring Deposits
	{
		key: 'rd_au_financial',
		name: 'Recurring Deposit - AU Financial Bank',
		emoji: '🏦',
		color: '#8B5CF6',
	},
	{
		key: 'rd_pnb_indian',
		name: 'Recurring Deposit - Punjab National Bank & Indian Bank',
		emoji: '🏦',
		color: '#3B82F6',
	},

	// Other Investments
	{
		key: 'fi_smart_deposit',
		name: 'FI Smart Deposit',
		emoji: '💡',
		color: '#84CC16',
	},
	{
		key: 'nps',
		name: 'National Pension Scheme',
		emoji: '👵',
		color: '#F97316',
	},
	{ key: 'ppf', name: 'Public Provident Fund', emoji: '📒', color: '#10B981' },

	// Gold ETF Components
	{
		key: 'axis_gold_etf',
		name: 'Axis Gold Exchange Traded Fund',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'birla_gold_etf',
		name: 'Birla Sun Life Gold ETF',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'kotak_gold_etf',
		name: 'Kotak Gold Exchange Traded Fund',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'nippon_gold_bees',
		name: 'Nippon India ETF Gold Bees',
		emoji: '🐝',
		color: '#F59E0B',
	},
	{
		key: 'zerodha_gold_etf',
		name: 'Zerodha Gold ETF',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'mirae_gold_etf',
		name: 'Mirae Asset Gold ETF',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{ key: 'dsp_gold_etf', name: 'DSP Gold ETF', emoji: '🥇', color: '#F59E0B' },
	{
		key: 'icici_gold_etf',
		name: 'ICICI Prudential Gold ETF',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'uti_gold_etf',
		name: 'UTI Gold Exchange Traded Fund',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'hdfc_gold_etf',
		name: 'HDFC Gold Exchange Traded Fund',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'quantum_gold_etf',
		name: 'Quantum Gold Fund ETF',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'sbi_gold_etf',
		name: 'SBI Gold Exchange Traded Scheme',
		emoji: '🥇',
		color: '#F59E0B',
	},
	{
		key: 'tata_gold_etf',
		name: 'TATA Gold Exchange Traded Fund',
		emoji: '🥇',
		color: '#F59E0B',
	},

	// Shoonya Shares Components
	{
		key: 'ambuja_cement',
		name: 'Ambuja Cement',
		emoji: '🏗️',
		color: '#6B7280',
	},
	{ key: 'berger_paint', name: 'Berger Paint', emoji: '🎨', color: '#3B82F6' },
	{ key: 'canara_bank', name: 'Canara Bank', emoji: '🏦', color: '#EF4444' },
	{
		key: 'castrol_india',
		name: 'Castrol India',
		emoji: '🛢️',
		color: '#DC2626',
	},
	{ key: 'coal_india', name: 'Coal India', emoji: '⛏️', color: '#000000' },
	{ key: 'gail', name: 'GAIL', emoji: '⛽', color: '#10B981' },
	{
		key: 'hindustan_zinc',
		name: 'Hindustan Zinc',
		emoji: '⚙️',
		color: '#F59E0B',
	},
	{ key: 'hdfc_bank', name: 'HDFC Bank', emoji: '🏦', color: '#EF4444' },
	{
		key: 'indian_oil',
		name: 'Indian Oil Corporation',
		emoji: '⛽',
		color: '#DC2626',
	},
	{ key: 'itc', name: 'ITC', emoji: '🚬', color: '#059669' },
	{ key: 'itc_hotels', name: 'ITC Hotels', emoji: '🏨', color: '#8B5CF6' },
	{
		key: 'mahindra',
		name: 'Mahindra & Mahindra',
		emoji: '🚜',
		color: '#3B82F6',
	},
	{ key: 'nalco', name: 'National Aluminium', emoji: '🏭', color: '#0EA5E9' },
	{ key: 'nmdc', name: 'NMDC', emoji: '⛏️', color: '#F59E0B' },
	{ key: 'ntpc_green', name: 'NTPC Green', emoji: '🌿', color: '#10B981' },
	{ key: 'ongc', name: 'ONGC', emoji: '🛢️', color: '#3B82F6' },
	{ key: 'powergrid', name: 'Powergrid', emoji: '⚡', color: '#F59E0B' },
	{ key: 'rec_ltd', name: 'REC Ltd.', emoji: '🏛️', color: '#DC2626' },
	{ key: 'reliance', name: 'Reliance', emoji: '🏢', color: '#0EA5E9' },
	{ key: 'sbi', name: 'State Bank of India', emoji: '🏦', color: '#F59E0B' },
	{ key: 'tata_power', name: 'TATA Power', emoji: '⚡', color: '#3B82F6' },
	{ key: 'tata_steel', name: 'TATA Steel', emoji: '🏭', color: '#6B7280' },
	{ key: 'vbl', name: 'VBL', emoji: '🍺', color: '#F97316' },

	// Shoonya ETF Components
	{ key: 'fmcg_ietf', name: 'FMCGIETF', emoji: '🛒', color: '#8B5CF6' },
	{ key: 'nifty_bees', name: 'NIFTYBEES', emoji: '🐝', color: '#059669' },
	{ key: 'silver_bees', name: 'SILVERBEES', emoji: '🐝', color: '#C0C0C0' },

	// Generic Categories for Daily/Monthly Savings
	{ key: 'cash_savings', name: 'Cash Savings', emoji: '💵', color: '#10B981' },
	{
		key: 'bank_savings',
		name: 'Bank Savings Account',
		emoji: '🏦',
		color: '#3B82F6',
	},
	{ key: 'piggy_bank', name: 'Piggy Bank', emoji: '🐷', color: '#EC4899' },
	{
		key: 'emergency_fund',
		name: 'Emergency Fund',
		emoji: '🚨',
		color: '#EF4444',
	},
	{
		key: 'goal_savings',
		name: 'Goal-based Savings',
		emoji: '🎯',
		color: '#8B5CF6',
	},
	{
		key: 'short_term',
		name: 'Short-term Savings',
		emoji: '📅',
		color: '#06B6D4',
	},
	{
		key: 'long_term',
		name: 'Long-term Savings',
		emoji: '📈',
		color: '#059669',
	},
];

export const ADMIN_CONFIG = {
	username: 'admin',
	password: 'admin123',
	email: 'admin@financetracker.com',
};

export const DIVIDEND_CATEGORIES = [
	{ key: 'ambujacemt', name: 'Ambuja Cements', emoji: '🏷️', color: '#000000' },
	{ key: 'bergepaint', name: 'Berger Paints', emoji: '🏷️', color: '#000000' },
	{ key: 'canbk', name: 'Canara Bank', emoji: '🏷️', color: '#000000' },
	{ key: 'castrolind', name: 'Castrol India', emoji: '🏷️', color: '#000000' },
	{ key: 'coalindia', name: 'Coal India', emoji: '🏷️', color: '#000000' },
	{ key: 'gail', name: 'GAIL (India)', emoji: '🏷️', color: '#000000' },
	{ key: 'hdfcbank', name: 'HDFC Bank', emoji: '🏷️', color: '#000000' },
	{
		key: 'hindunilvr',
		name: 'Hindustan Unilever',
		emoji: '🏷️',
		color: '#000000',
	},
	{ key: 'hindzinc', name: 'Hindustan Zinc', emoji: '🏷️', color: '#000000' },
	{ key: 'ioc', name: 'Indian Oil Corporation', emoji: '🏷️', color: '#000000' },
	{ key: 'itc', name: 'ITC Limited', emoji: '🏷️', color: '#000000' },
	{ key: 'itchotels', name: 'ITC Hotels', emoji: '🏷️', color: '#000000' },
	{ key: 'm&m', name: 'Mahindra & Mahindra', emoji: '🏷️', color: '#000000' },
	{ key: 'nationalum', name: 'NALCO', emoji: '🏷️', color: '#000000' },
	{ key: 'nmdc', name: 'NMDC Limited', emoji: '🏷️', color: '#000000' },
	{
		key: 'ntpcgreen',
		name: 'NTPC Green Energy',
		emoji: '🏷️',
		color: '#000000',
	},
	{ key: 'ongc', name: 'ONGC', emoji: '🏷️', color: '#000000' },
	{ key: 'powergrid', name: 'Power Grid Corp', emoji: '🏷️', color: '#000000' },
	{ key: 'recltd', name: 'REC Limited', emoji: '🏷️', color: '#000000' },
	{
		key: 'reliance',
		name: 'Reliance Industries',
		emoji: '🏷️',
		color: '#000000',
	},
	{ key: 'sbin', name: 'State Bank of India', emoji: '🏷️', color: '#000000' },
	{ key: 'tatapower', name: 'Tata Power', emoji: '🏷️', color: '#000000' },
	{ key: 'tatasteel', name: 'Tata Steel', emoji: '🏷️', color: '#000000' },
	{ key: 'vbl', name: 'Varun Beverages', emoji: '🏷️', color: '#000000' },
	{
		key: 'tcs',
		name: 'Tata Consultancy Services',
		emoji: '🏷️',
		color: '#000000',
	},
];
