export const BANK_LIST = [
	'State Bank of India (SBI)',
	'HDFC Bank',
	'ICICI Bank',
	'Punjab National Bank (PNB)',
	'Bank of Baroda',
	'Axis Bank',
	'Kotak Mahindra Bank',
	'Canara Bank',
	'Union Bank of India',
	'Bank of India',
	'IndusInd Bank',
	'Yes Bank',
	'IDBI Bank',
	'Central Bank of India',
	'Indian Bank',
	'IDFC First Bank',
	'RBL Bank',
	'Bandhan Bank',
	'Federal Bank',
	'South Indian Bank',
	'Karur Vysya Bank',
	'Karnataka Bank',
	'City Union Bank',
	'Dhanlaxmi Bank',
	'DCB Bank',
	'Jammu & Kashmir Bank',
	'Punjab & Sind Bank',
	'UCO Bank',
	'Bank of Maharashtra',
	'Vijaya Bank',
];
